"""Add file_imports and import_data tables

Revision ID: 11679b22f776
Revises: 53bd9917126f
Create Date: 2026-01-07 12:55:35.261477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11679b22f776'
down_revision: Union[str, Sequence[str], None] = '53bd9917126f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('import_type', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_imports_project_id'), 'file_imports', ['project_id'], unique=False)
    op.create_table('import_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_import_id', sa.UUID(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('values', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_import_id'], ['file_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_data_file_import_id'), 'import_data', ['file_import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_data_file_import_id'), table_name='import_data')
    op.drop_table('import_data')
    op.drop_index(op.f('ix_file_imports_project_id'), table_name='file_imports')
    op.drop_table('file_imports')
    # ### end Alembic commands ###
